"""
Speed ladder for race-day binary search.

    cd src
    python -m raceline.ladder --targets 60 50 40 35
    python -m raceline.ladder --k 0.35            # one rung at a given level

One scalar k in [0, 1] scales the flight envelope between a SAFE FLOOR
and the race limits in config/vehicle.toml:

    k = 0   tilt 20 deg, v_max 5 m/s, slew 40, a_lat_margin 0.7
    k = 1   the [limits]/[planner] values of the race config

and every per-gate knob in the planner (lateral / z offsets, tilt
overrides, stubs) is ZEROED, so each crossing goes through the centre of
the opening with the full 0.60 m of margin on every side. The race plan
itself (plan_RACE, per-gate knobs, k = 1) stays what it is; the ladder
covers everything below it.

For each target time the model's predicted total is bisected on k; the
rung is written as

    config/ladder/vehicle_<T>s.toml     the race toml with 4 lines changed
    out/plans/plan_LADDER_<T>s.json/.png

and flown with

    python race.py --config config/ladder/vehicle_60s.toml \
                   --traj out/plans/plan_LADDER_60s.json

Race-day procedure: fly the slowest rung. Clean -> fly the fastest.
Fails -> the midpoint. Each step halves the interval. Targets are MODEL
times; the flown race rung runs ~10 % over its model, slower rungs less.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import io
import json
import math
import re
import sys
from pathlib import Path

import numpy as np

from raceline import planner as pm
from raceline import render_plan
from raceline.config import load_config, DEFAULT_CONFIG_PATH

REPO = Path(__file__).resolve().parents[2]
LADDER_DIR = REPO / "config" / "ladder"
PLANS_DIR = REPO / "out" / "plans"

# safe floor of the envelope (k = 0); the ceiling is the race config
# THE LEVERS. k = 0 is the safe end, k = 1 is whatever the config says (the
# race limits). Each rung is a full solve; the time is whatever comes out.
# vz_up_max is NOT a lever: a climbing turn crosses off centre above about
# 1.25 m/s whatever the speed (race_297 at 1.75), and the cap costs 1 s.
FLOOR = {"max_tilt_deg": 20.0, "v_max_mps": 5.0,
         "a_lat_rate_max": 40.0, "a_lat_margin": 0.7}
SECTION_OF = {"max_tilt_deg": "limits", "v_max_mps": "limits",
              "a_lat_rate_max": "limits", "a_lat_margin": "planner"}
FRAME_MARGIN_M = 0.75 - 0.15     # half opening minus body radius

# CAMERA-AWARE TILT CAP. A plan is only flyable on vision if the next gate
# stays in the frame on the approach. A gate at the drone's own height sits
# (pitch - mount) above the optical axis, so the pitch may not exceed
# mount + vertical half field of view - a margin for roll and gate height.
# Set from --cam-tilt / --cam-hfov; None = the airframe limit alone.
TILT_CAP_DEG = None
CAM_TAG = ""
LOOK_MARGIN_DEG = 8.0


def camera_tilt_cap(mount_deg: float, hfov_deg: float) -> float:
    vhalf = math.degrees(math.atan(math.tan(math.radians(hfov_deg / 2.0)) * 9.0 / 16.0))
    return mount_deg + vhalf - LOOK_MARGIN_DEG


def envelope(k: float, race_cfg) -> dict:
    k = min(1.0, max(0.0, k))
    out = {}
    for key, lo in FLOOR.items():
        hi = float(getattr(getattr(race_cfg, SECTION_OF[key]), key))
        out[key] = lo + k * (hi - lo)
    if TILT_CAP_DEG is not None:
        out["max_tilt_deg"] = min(out["max_tilt_deg"], TILT_CAP_DEG)
    return out


def write_rung_toml(race_path: Path, env: dict, out_path: Path, k: float) -> Path:
    """The race toml with only the envelope lines replaced (comments and
    every other section untouched, so the loader's schema check passes)."""
    text = race_path.read_text(encoding="utf-8")
    for key, val in env.items():
        pat = re.compile(rf"^({re.escape(key)}\s*=\s*)([-\d.eE+]+)(.*)$", re.M)
        text, n = pat.subn(lambda m: f"{m.group(1)}{val:.3f}{m.group(3)}", text, count=1)
        if n != 1:
            raise SystemExit(f"{race_path.name}: key {key} not found")
    header = (f"# LADDER RUNG k={k:.3f} generated by raceline.ladder from "
              f"{race_path.name}; only max_tilt_deg / v_max_mps / "
              f"a_lat_rate_max / a_lat_margin differ from the race config."
              + (f" Camera {CAM_TAG[4:]} (mount_lens deg): plan tilt capped at {TILT_CAP_DEG:.1f} deg." if TILT_CAP_DEG is not None else "")
              + "\n")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header + text, encoding="utf-8")
    return out_path


@contextlib.contextmanager
def centred_crossings():
    """Zero the planner's per-gate knobs (keep only the START-role stub)."""
    saved = {n: getattr(pm, n) for n in ("POSE_LAT_OFFSET_M", "POSE_Z_OFFSET_M",
                                         "POSE_TILT_OVERRIDE_DEG", "PRE_STUB_M",
                                         "POST_STUB_M")}
    try:
        pm.POSE_LAT_OFFSET_M = {}
        pm.POSE_Z_OFFSET_M = {}
        pm.POSE_TILT_OVERRIDE_DEG = {}
        pm.PRE_STUB_M = {g: v for g, v in saved["PRE_STUB_M"].items() if g == "g0"}
        pm.POST_STUB_M = {}
        yield
    finally:
        for n, v in saved.items():
            setattr(pm, n, v)


def plan_at(k: float, race_cfg, tmp_toml: Path):
    """Plan the course at envelope level k. Returns (plan, cfg)."""
    env = envelope(k, race_cfg)
    write_rung_toml(race_cfg.path, env, tmp_toml, k)
    cfg = load_config(tmp_toml)
    with centred_crossings(), contextlib.redirect_stdout(io.StringIO()):
        p = pm.plan(cfg)
    return p, cfg


def crossing_margins(plan_dict: dict) -> list[tuple[str, float]]:
    arr = np.asarray(plan_dict["samples"], dtype=float)
    P = arr[:, 1:4]
    S = np.concatenate([[0.0], np.cumsum(np.linalg.norm(np.diff(P, axis=0), axis=1))])
    out = []
    for e in plan_dict["events"]:
        h = e.get("heading_rad")
        if h is None:
            continue
        nx, ny = math.cos(h), math.sin(h)
        sd = (P[:, 0] - e["x"]) * nx + (P[:, 1] - e["y"]) * ny
        win = np.where(np.abs(S - e["s"]) < 4.0)[0]
        k = next((i for i in win[:-1] if sd[i] < 0 <= sd[i + 1]), None)
        if k is None:
            out.append((e["label"], float("nan")))
            continue
        f = sd[k] / (sd[k] - sd[k + 1])
        q = P[k] + (P[k + 1] - P[k]) * f
        lat = -(q[0] - e["x"]) * ny + (q[1] - e["y"]) * nx
        dz = q[2] - e["z"]
        out.append((e["label"], FRAME_MARGIN_M - max(abs(lat), abs(dz))))
    return out


def solve_rung(target_s: float, race_cfg, tmp_toml: Path, tol_s: float = 0.4,
               max_eval: int = 12, verbose: bool = True):
    """Bisect k so the model's total time hits target_s (monotonic: more
    envelope = faster). Returns (k, plan, cfg) or None if unreachable."""
    lo, hi = 0.0, 1.0
    p_lo, _ = plan_at(lo, race_cfg, tmp_toml)
    p_hi, _ = plan_at(hi, race_cfg, tmp_toml)
    t_lo, t_hi = float(p_lo.total_s), float(p_hi.total_s)
    if verbose:
        print(f"  envelope range: k=0 -> {t_lo:.1f} s, k=1 (centred) -> {t_hi:.1f} s")
    if target_s > t_lo + tol_s:
        print(f"  target {target_s:.0f} s is slower than the safe floor ({t_lo:.1f} s); "
              "using the floor")
        return 0.0, p_lo, load_config(write_rung_toml(race_cfg.path, envelope(0.0, race_cfg), tmp_toml, 0.0))
    if target_s < t_hi - tol_s:
        print(f"  target {target_s:.0f} s is faster than centred crossings allow "
              f"({t_hi:.1f} s)" + (f" with the camera's tilt cap of {TILT_CAP_DEG:.0f} deg" if TILT_CAP_DEG is not None else "; that is plan_RACE territory"))
        return None
    best = (1.0, p_hi)
    for _ in range(max_eval):
        k = 0.5 * (lo + hi)
        p, _ = plan_at(k, race_cfg, tmp_toml)
        t = float(p.total_s)
        if verbose:
            print(f"    k={k:.3f}  model {t:.2f} s  contacts {p.meta.get('frame_violations', 0)}")
        best = (k, p)
        if abs(t - target_s) <= tol_s:
            break
        if t > target_s:
            lo = k          # too slow: open the envelope
        else:
            hi = k
    k, p = best
    # contact-clean or step the envelope down until it is
    while p.meta.get("frame_violations", 0) and k > 0.0:
        k = max(0.0, k - 0.02)
        p, _ = plan_at(k, race_cfg, tmp_toml)
        if verbose:
            print(f"    contact -> k={k:.3f}  model {float(p.total_s):.2f} s  "
                  f"contacts {p.meta.get('frame_violations', 0)}")
    cfg = load_config(write_rung_toml(race_cfg.path, envelope(k, race_cfg), tmp_toml, k))
    return k, p, cfg


def emit(tag: str, k: float, p, cfg, race_cfg) -> dict:
    toml_path = LADDER_DIR / f"vehicle_{tag}.toml"
    write_rung_toml(race_cfg.path, envelope(k, race_cfg), toml_path, k)
    cfg = load_config(toml_path)                 # plan must carry THIS sha
    cfg.path = toml_path.relative_to(REPO)       # recorded as config_path: repo-relative, container-resolvable
    with centred_crossings(), contextlib.redirect_stdout(io.StringIO()):
        p = pm.plan(cfg)
    plan_path = PLANS_DIR / f"plan_LADDER_{tag}.json"
    pm.write_plan(p, plan_path)
    try:
        render_plan.render(p, plan_path.with_suffix(".png"))
    except Exception as ex:                      # noqa: BLE001
        print(f"    render skipped: {ex}")
    d = json.load(open(plan_path, encoding="utf-8"))
    margins = crossing_margins(d)
    env = envelope(k, race_cfg)
    row = {"tag": tag, "k": round(k, 3), "model_s": round(float(p.total_s), 2),
           "contacts": int(p.meta.get("frame_violations", 0)),
           "min_margin_m": round(min(m for _, m in margins if not math.isnan(m)), 2),
           "tilt_deg": round(env["max_tilt_deg"], 1), "v_max": round(env["v_max_mps"], 1),
           "slew": round(env["a_lat_rate_max"], 0), "a_lat_margin": round(env["a_lat_margin"], 2),
           "toml": str(toml_path.relative_to(REPO)), "plan": str(plan_path.relative_to(REPO))}
    return row


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--targets", type=float, nargs="*", default=[60, 50, 40, 35],
                    help="model total times (s) to build rungs for")
    ap.add_argument("--k", type=float, default=None, help="build ONE rung at this level instead")
    ap.add_argument("--config", default=None, help="race vehicle.toml (default config/vehicle.toml)")
    ap.add_argument("--cam-tilt", type=float, default=None, help="camera mount tilt above body forward, deg")
    ap.add_argument("--cam-hfov", type=float, default=None, help="camera horizontal field of view, deg")
    args = ap.parse_args(argv)
    global TILT_CAP_DEG, CAM_TAG
    if (args.cam_tilt is None) != (args.cam_hfov is None):
        raise SystemExit("--cam-tilt and --cam-hfov go together")
    if args.cam_tilt is not None:
        TILT_CAP_DEG = camera_tilt_cap(args.cam_tilt, args.cam_hfov)
        CAM_TAG = f"_cam{args.cam_tilt:.0f}_{args.cam_hfov:.0f}"
        print(f"camera {args.cam_tilt:.0f} deg mount, {args.cam_hfov:.0f} deg lens: plan tilt capped at {TILT_CAP_DEG:.1f} deg")

    race_cfg = load_config(args.config or DEFAULT_CONFIG_PATH)
    tmp_toml = LADDER_DIR / "_probe.toml"
    rows = []
    if args.k is not None:
        p, cfg = plan_at(args.k, race_cfg, tmp_toml)
        tag = f"k{int(round(args.k * 100)):03d}{CAM_TAG}"
        rows.append(emit(tag, args.k, p, cfg, race_cfg))
    else:
        for target in sorted(args.targets, reverse=True):
            print(f"rung {target:.0f} s")
            res = solve_rung(target, race_cfg, tmp_toml)
            if res is None:
                continue
            k, p, cfg = res
            rows.append(emit(f"{target:.0f}s{CAM_TAG}", k, p, cfg, race_cfg))
    tmp_toml.unlink(missing_ok=True)

    print()
    print(f"{'rung':>6} {'k':>6} {'model':>7} {'cont':>4} {'margin':>7} {'tilt':>5} {'v_max':>5} {'slew':>5} {'a_lat':>5}  files")
    for r in rows:
        print(f"{r['tag']:>6} {r['k']:6.3f} {r['model_s']:7.2f} {r['contacts']:4d} "
              f"{r['min_margin_m']:7.2f} {r['tilt_deg']:5.1f} {r['v_max']:5.1f} "
              f"{r['slew']:5.0f} {r['a_lat_margin']:5.2f}  {r['toml']}  {r['plan']}")
    index = LADDER_DIR / f"ladder{CAM_TAG}.json"
    index.write_text(json.dumps(rows, indent=1) + "\n", encoding="utf-8")
    print(f"\nindex -> {index}")
    print("fly a rung:  python race.py --config <toml> --traj <plan>")
    return 0


if __name__ == "__main__":
    sys.exit(main())
